version: '3.8'

services:
  flask_app:
    container_name: flask_app
    build: .
    command: sh -c "pip install -r requirements.txt && python3 main.py"

    depends_on:
      - mongodb

    volumes:
      - ./:/var/app/

    ports:
      - 5000:5000

  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - mongo_data:/var/lib/mongodb
    ports:
      - 27017:27017


volumes:
  mongo_data:

networks:
  default:
    external:
      name: motivation-network
